CREATE TABLE IF NOT EXISTS pages(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  meta_data JSONB NOT NULL DEFAULT '{}'::JSONB,
  word_count INTEGER NOT NULL DEFAULT 0,
  is_indexed BOOLEAN NOT NULL DEFAULT FALSE,
  domain_id UUID NOT NULL,
  CONSTRAINT fk_pages_domains FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
);