// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Domain struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Domain    string
}

type Page struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Url       string
	Title     string
	MetaData  json.RawMessage
	WordCount int32
	IsIndexed bool
	DomainID  uuid.UUID
}

type PageReferral struct {
	ReferralID uuid.UUID
	PageID     uuid.UUID
}

type Word struct {
	ID   uuid.UUID
	Word string
}

type WordPage struct {
	WordID    uuid.UUID
	PageID    uuid.UUID
	WordCount int32
}
